web/views.py
from flask import (
    Blueprint,
    Response,
    flash,
    redirect,
    render_template,
    session,
    url_for,
)

from base.data import fetch_data, localization, parser
from base.operation import operation, report

from .forms import (
    SearchApartmentForm,
    SearchByCategories,
    SearchHouseForm,
    validate_city_name,
)

views = Blueprint("views", __name__)


@views.route("/", methods=["GET", "POST"])
def home_view() -> Response | str:
    form = SearchByCategories()
    if form.validate_on_submit():
        category = form.category.data
        session["category_data"] = {
            "category": form.category.data,
            "price_min": form.price_min.data,
            "price_max": form.price_max.data,
        }
        check_city = localization.Localization(
            validate_city_name(form.city.data)
        ).return_localization_data()
        if check_city:
            session["city_data"] = {"city": validate_city_name(form.city.data)}
            if category == "1307":
                return redirect(url_for("views.search_apartment_view"))
            elif category == "1309":
                return redirect(url_for("views.search_house_view"))
        flash("City not found", category="error")

    return render_template("home.html", form=form)


@views.route("/search_apartment", methods=["GET", "POST"])
def search_apartment_view() -> Response | str:
    form = SearchApartmentForm()

    if form.validate_on_submit():
        category_data = session.get("category_data")
        if category_data:
            session["apartment_data"] = {
                "build_type": form.build_type.data,
                "rooms": form.rooms.data,
                "furniture": form.furniture.data,
                "area_min": form.area_min.data,
                "area_max": form.area_max.data,
            }

            return redirect(url_for("views.results_view"))

    return render_template("search_apartment.html", form=form)


@views.route("/search_house", methods=["GET", "POST"])
def search_house_view() -> Response | str:
    form = SearchHouseForm()

    if form.validate_on_submit():
        category_data = session.get("category_data")
        if category_data:
            session["house_data"] = {
                "build_type": form.build_type.data,
                "area_min": form.area_min.data,
                "area_max": form.area_max.data,
                "area_plot_min": form.area_plot_min.data,
                "area_plot_max": form.area_plot_max.data,
            }

            return redirect(url_for("views.results_view"))

    return render_template("search_house.html", form=form)


def get_result_data(url: str):
    x = parser.Parser(fetch_data.FetchData(url).fetch_data())
    d = x.data_parser()
    s = operation.return_newest_offers(d)
    y = operation.return_average_price(d)
    f = operation.return_average_price_per_meter(d)
    v = operation.return_most_expensive_offer(d)
    i = operation.return_most_expensive_offer_per_meter(d)
    u = operation.return_offer_largest_area_building(d)
    l = operation.return_offer_largest_area_plot(d)
    return d, s, y, f, v, i, u, l


@views.route("/results", methods=["GET", "POST"])
def results_view() -> Response | str:
    category_data = session.get("category_data")
    city_data = session.get("city_data")

    if category_data and city_data:
        category = category_data["category"]
        city = city_data["city"]
        if category == "1307":
            apartment_data = session.get("apartment_data")
            localization_data = localization.Localization(city)
            url = fetch_data.UrlBuilderApartment().build_url(
                build_type=apartment_data["build_type"],
                furrooms=apartment_data["rooms"],
                niture=apartment_data["furniture"],
                area_min=apartment_data["area_min"],
                area_max=apartment_data["area_max"],
                city_id=localization_data.return_localization_data().city_id,
                region_id=localization_data.return_localization_data().region_id,
            )
        elif category == "1309":
            house_data = session.get("house_data")
            localization_data = localization.Localization(city)
            url = fetch_data.UrlBuilderHouse().build_url(
                build_type=house_data["build_type"],
                area_min=house_data["area_min"],
                area_max=house_data["area_max"],
                plot_area_min=house_data["area_plot_min"],
                plot_area_max=house_data["area_plot_max"],
                city_id=localization_data.return_localization_data().city_id,
                region_id=localization_data.return_localization_data().region_id,
            )

        d, s, y, f, v, i, u, l = get_result_data(url)

        return render_template(
            "results.html",
            data_list=d,
            newest_offers=s,
            average_price=y,
            average_price_per_meter=f,
            most_expensive_offer=v,
            most_expensive_offer_per_meter=i,
            largest_area_building=u,
            largest_area_plot=l,
        )

    return render_template("results.html")


def get_report_data():
    report_apartment_data = report.ReportApartment().return_report()
    report_house_data = report.ReportHouse().return_report()

    report_apartment_average_price = (
        report.ReportApartment().return_weekly_average_price(report_apartment_data)
    )
    report_apartment_average_price_per_sqr_m = (
        report.ReportApartment().return_weekly_average_area_price(report_apartment_data)
    )

    report_house_average_price = report.ReportHouse().return_weekly_average_price(
        report_house_data
    )
    report_house_average_price_per_sqr_m = (
        report.ReportHouse().return_weekly_average_area_price(report_house_data)
    )

    return (
        report_apartment_data,
        report_house_data,
        report_apartment_average_price,
        report_house_average_price,
        report_apartment_average_price_per_sqr_m,
        report_house_average_price_per_sqr_m,
    )


@views.route("/report", methods=["GET", "POST"])
def report_view() -> Response | str:
    (
        report_apartment_data,
        report_house_data,
        report_apartment_average_price,
        report_house_average_price,
        report_apartment_average_price_per_sqr_m,
        report_house_average_price_per_sqr_m,
    ) = get_report_data()

    return render_template(
        "report.html",
        report_apartment_data=report_apartment_data,
        report_house_data=report_house_data,
        report_apartment_average_price=report_apartment_average_price,
        report_house_average_price=report_house_average_price,
        report_apartment_average_price_per_sqr_m=report_apartment_average_price_per_sqr_m,
        report_house_average_price_per_sqr_m=report_house_average_price_per_sqr_m,
    )

web/templates/base/footer.html
<footer class="text-center text-lg-start bg-light text-muted">
    <section class="">
      <div class="container text-center text-md-start mt-4">
        <div class="row mt-5">
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4 mt-3">
              <i class="fas fa-gem me-3"></i>OLX Analitics 
            </h6>
            <p>
                Ut ea facere quas ducimus. Dolore excepturi corrupti reprehenderit qui facilis. Et officiis est qui cumque voluptates ullam rerum qui.
            </p>
          </div>

          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4 mt-3">
              About me
            </h6>
            <p>
              <a href="https://github.com/DEENUU1/" class="text-reset">GitHub</a>
            </p>
            <p>
              <a href="https://www.linkedin.com/in/kacper-wlodarczyk/" class="text-reset">LinkedIn</a>
            </p>
          </div>
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4 mt-3">
              Useful links
            </h6>
            <p>
              <a href="https://www.olx.pl/" class="text-reset">OLX</a>
            </p>
            <p>
              <a href="{{url_for('auth.register')}}" class="text-reset">Register</a>
            </p>
          </div>
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase fw-bold mb-4 mt-3">Contact</h6>
            <p>Address: New York, NY 10012, US</p>
            <p>Email: info@example.com</p>
            <p>Phone number:  01 234 567 89</p>
          </div>
        </div>
      </div>
    </section>
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2023 Copyright:
      <a class="text-reset fw-bold" href="https://github.com/DEENUU1/">Kacper Włodarczyk</a>
    </div>
  </footer>

web/templates/base/navigation_bar.html
<nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
      <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <a class="navbar-brand mt-2 mt-lg-0" href="/">
            <img
                src="static/images/analytics.png"
                height="40"
                alt="MDB Logo"
                loading="lazy"
            />
            </a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.register')}}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.report_view')}}">Reports</a>
            </li>
            </ul>
        </div>

      </div>
    </div>
  </nav>